spring:
  application:
    name: worksphere-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/worksphere
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true